--SELEZIONARE I CLIENTI:
SELECT EMAIL AS CUSTOMERS
FROM ORDERS;


--SELEZIONARE GLI ACCOUNT CHE HANNO INSERITO COME INDIRIZZO DI CONSEGNA ‘Napoli’
SELECT EMAIL
FROM RECIPIENT
WHERE CITY='Napoli';


--SELEZIONARE GLI ACCOUNT CHE HANNO INSERITO COME INDIRIZZO DI CONSEGNA ‘Napoli’ o ‘San Giorgio a Cremano’
SELECT EMAIL
FROM RECIPIENT
WHERE CITY='Napoli' OR CITY = ‘San Giorgio a Cremano’;


--SELEZIONARE IL CODICE DI TUTTI I PRODOTTO VENDUTI
SELECT PROD_CODE
FROM SOLD_ITEMS;



--SELEZIONARE IL CODICE DEL PRODOTTO MAGGIORMENTE VENDUTO IN UN ORDINE PER CLIENTE
SELECT PROD_CODE
FROM SOLD_ITEMS
WHERE QUANTITY = (SELECT MAX(QUANTITY) FROM SOLD_ITEMS);



--SELEZIONARE IL NUMERO DI FORNI VENDUTI (CODICE INIZIA PER ‘OVN’)
SELECT SUM(QUANTITY) AS OVEN_SOLD FROM SOLD_ITEMS WHERE PROD_CODE LIKE 'OVN%';


--SELEZIONARE I CLIENTI E COSA HANNO ACQUISTATO
SELECT ORDERS.EMAIL AS CUSTOMER_EMAIL, SOLD_ITEMS.PROD_CODE AS PRODUCT_SOLD
FROM SOLD_ITEMS JOIN ORDERS ON ORDERS.ORDER_ID = SOLD_ITEMS.ORDER_ID;


--SELEZIONARE I COLORI DISPONIBILI PER UN PRODOTTO ORDINATO (LAVASTOVIGLIE)
SELECT DISTINCT DISHWASHER.PRODUCT_CODE, DISHWASHER.COLOUR
FROM DISHWASHER JOIN SOLD_ITEMS ON DISHWASHER.PRODUCT_CODE = SOLD_ITEMS.PROD_CODE;


--SELEZIONARE IL NUMERO DI PRODOTTI CON UNO SCONTO MAGGIORE O UGUALE AL 10%
SELECT COUNT(PRODUCT_CODE) AS PRODUCTS_WITH_10_DISCOUNT_OR_MORE
FROM PRODUCT
WHERE DISCOUNT >= 10;



--SELEZIONARE LE CUCINE AVENTI PIU’ DEL 10% DI SCONTO E IL RELATIVO PREZZO
SELECT PRODUCT_CODE AS STOVE_WITH_10_DISCOUNT_OR_MORE, PRICE
FROM PRODUCT
WHERE DISCOUNT >= 10 AND PRODUCT_CODE LIKE 'STV%'
ORDER BY PRICE;


--SELEZIONARE INTESTATARI, CARTE DI CREDITO E DATA DI SCADENZA ORDINATE CRESCENTEMENTE SECONDO LA DATA DI SCADENZA
SELECT ACCOUNT_HOLDER, CARD_NUM, EXPIRING_DATE
FROM CREDIT_CARD
ORDER BY EXPIRING_DATE;


--SELEZIONARE UN FORNO DI TIPO ELETTRICO E COLORE BIANCO E IL RELATIVO PREZZO
SELECT DISTINCT PRODUCT.PRODUCT_CODE, PRODUCT.PRICE
FROM PRODUCT JOIN OVEN ON PRODUCT.PRODUCT_CODE = OVEN.PRODUCT_CODE
WHERE OVEN.TYPE = 'electric' AND OVEN.COLOUR = 'white';



--SELEZIONARE TUTTI GLI UTENTI CHE SONO REGISTRATI AL SITO MA CHE NON HANNO ANCORA EFFETTUATO ORDINI
SELECT EMAIL FROM ACCOUNT 
WHERE EMAIL NOT IN (SELECT DISTINCT EMAIL FROM ORDERS INNER
JOIN SOLD_ITEMS
ON ORDERS.ORDER_ID = SOLD_ITEMS.ORDER_ID);



--SELEZIONARE EMAIL, INDIRIZZO, CITTA’ E CAP DI TUTTI GLI UTENTI CHE SONO REGISTRATI AL SITO, NON HANNO EFFETTUATO ANCORA ORDINI E USUFRUISCONO DEL SERVIZIO DI POSTA DI GOOGLE “@gmail**”, (in modo da poter fornire loro un ADS personalizzato quando accedono al loro servizio) ORDINATI IN ORDINE ALFABETICO
SELECT EMAIL, TELEPHONE_NUM, ADDRESS, CITY, ZIP_CODE FROM RECIPIENT 
WHERE EMAIL NOT IN (SELECT DISTINCT EMAIL FROM ORDERS)
AND EMAIL LIKE '%gmail%'
ORDER BY EMAIL;



--SELEZIONARE UN IL CODICE PRODOTTO, PREZZO, SCONTO E PREZZO DOPO UNO SCONTO DI UN FORNO AVENTE COLORE NERO, TIPOLOGIA GAS, SENZA TIMER E IL CUI PREZZO DOPO LO SCONTO SIA INFERIORE A 350 EURO
SELECT DISTINCT PRODUCT.PRODUCT_CODE,
PRICE AS ORIGINAL_PRICE,
DISCOUNT,
(PRICE - (DISCOUNT*PRICE/100)) AS PRICE_AFTER_DISCOUNT
FROM PRODUCT INNER
JOIN OVEN ON PRODUCT.PRODUCT_CODE = OVEN.PRODUCT_CODE
WHERE OVEN.COLOUR = 'black'
AND OVEN.TYPE = 'gas'
AND OVEN.TIMER = 'no'
AND (PRICE - (DISCOUNT*PRICE/100)) < 350;

